### ISSUE TITLE
Look, I snap my story again

### ISSUE THREAD

**Issue by hakankocyigit** [marzika/Snapprefs#174] opened 2016-08-22 08:13 UTC
Coming back to my story, I look at Snaps. When the application is turned off and I have to look at the snaps I've ever seen again.
Snapprefs 2.0.0
Snapchat 9.31.1.0 
Xperia Z3C 6.0.1 Rom

**Comment by Ketrel** [comment] 2016-08-22 20:41
If you're saying that stories you've read keep getting marked unread when you fully close snapchat (reboot, force stop, etc), then I can confirm that happens to me too

Snapprefs 2.0.0
Snapshat 9.31.1.0
Nexus 5 Android 4.4.4 ROM

I have kill app bound to a long press of my task switcher key, so I can easily test this.

**Comment by hakankocyigit** [comment] 2016-08-22 20:44
English is not good I do not know how I'll test 😑

**Comment by rapperskull** [comment] 2016-08-22 21:52
After viewing the stories, pull down to refresh and wait for it to happen, then reopen Snapchat to see if the issue is solved. It works for me.

**Comment by hakankocyigit** [comment] 2016-08-22 22:31
@rapperskull I tried but I can not. also it had the same error in version 9.21.1.0.

**Comment by marzika** [comment] 2016-08-31 21:12
Tap through them before closing the app.

**Closed as completed by marzika** 2016-08-31 21:12 UTC

**Comment by zevozki** [comment] 2016-09-12 11:27
I have noticed that too and tried to reproduce the issue and I can say it happens while you watching story and the ( image/video playing)  then you suddenly kills the app or phone reboot.  Then When you re lunch the app you will see all the stories already un read again and even direct snaps video or photos are also become unread (not all of them, just the snaps you saw recently). 

I know its closed but it worth to add info not mentioned.
