### ISSUE TITLE
Snapchat Version 9.31.1.0 no longer supported by Snapchat.

### ISSUE THREAD

**Issue by joern-h** [marzika/Snapprefs#302] opened 2016-11-01 13:08 UTC
My Snapchat Version 9.31.1.0 crashes constantly.

I think this is caused by Snapchat, because they no longer Support version 9.31.1.0 and a uninstall of Snapprefs does not solved it. Also the logs in Xposed dosent showed me the problem. (yes i can read logs and mostly i find the solution)

After a reinstall snapchat says at the login that my App version or my OS version is no longer supported.

Kind regards,
Joern2410

**Comment by M1kep** [comment] 2016-11-01 13:39
Sounds about right, alot of people are having crashes on 9.31.1

And a side note I HIGHLY doubt that all of the features are going to work as expected on 9.42.2 and we WILL NOT provide any form of support for errors relating to your modifications. We will be releasing a 9.39.5 build ASAP.

**Comment by guihkx** [comment] 2016-11-01 18:24
@M1kep Does the development build support the latest version of Snapchat or a specific one? Thank you.

**Comment by M1kep** [comment] 2016-11-01 18:25
Latest dev builds are for SC 9.39.5

**Comment by M1kep** [comment] 2016-11-01 18:25
@GUiHKX

**Comment by gordiclazar** [comment] 2016-11-02 13:02
@Joern2410
Can you make and drop a download link of your modded SC 9.31.1.0 apk on google drive or somewhere to try it out? 
Btw...(just addition)
Im having exact same problem as you since yesterday, it doesnt appear to crash...but rather it closes itself! I think SC dev team has made it that they can remotely close/crash your snapchat when they register that you are on 9.31.1.0 version since they probably know that that one is latest supported by Snapprefs.

**Comment by JamesCaywood** [comment] 2016-11-02 14:25
Dang on mine it doesn't work :S on 9.39.5 snappref  :S on android 4.3 I think note 2

**Comment by M1kep** [comment] 2016-11-02 15:37
@Joern2410 Please do not distribute any self modified APK's of SP.
@gordiclazar If you want to run a dev build(Much more stable than what @Joern2410 is talking about) download the dev build from: http://138.68.21.49:8080/job/SNAPPREFSDev/lastSuccessfulBuild/
That is build for 9.39.5

**Comment by gordiclazar** [comment] 2016-11-02 15:46
@M1kep  I asked him for his modded apk myself, i will install it on my own risk it has nothing to do with snapprefs. I believe him apk will work, it is not a v9.42 SC, but its rather a v9.31 which is modified to trick snapchat server that it is newer version so it wont crash on its own by server! 

@Joern2410 i would like you to send me download link directly if they wont allow for link to be dropped in this thread. I will give you my email when you respond to my comment! Thanks dude

**Comment by quorn23** [comment] 2016-11-02 15:52
It has nothing to do with Snapprefs, correct. Please don't abuse Snappref Issues for any modded versions of an App. Snappref doesn't modify SC, nor does it patch it etc. This is not the right channel for this.

**Comment by gordiclazar** [comment] 2016-11-02 16:19
@quorn23
I disagree, this is not a forum where total newbies ask most stupid questions. I believe discussing topics such as this can help marz and others by possibly giving new ideas. I believe that everyone using current snapprefs 2.0.0 with SC 9.31.1 will not be able to use it at all anymore in next few days. I repeat myself, but i think its solely due to version that is used by snapprefs and SC servers automatically disconnect anyone using v9.31.1

**Comment by M1kep** [comment] 2016-11-02 16:20
@gordiclazar The issue is that we do not in any way support or recommend modification of SC in any way, nor do we wish to be affiliated with that.

**Comment by gordiclazar** [comment] 2016-11-02 16:28
@M1kep I do not support modified apps neither. Wouldnt trust or use any of them. But the modification in question is the simplest possible. As he presented it, he ONLY modified version number in the build, in attempt to trick SC servers into not automatically disconnecting when u start snapchat. Even i can do this myself(even tho i never tried it before) but i am in quite a mess and i do not have time to do it now(since i believe to me it would take around 10h of work to learn it)

**Comment by Andrerm124** [comment] 2016-11-02 16:32
@gordiclazar It's a legal thing, we cannot modify and distribute copyrighted material on this page

**Comment by BornInSuriname** [comment] 2016-11-02 16:53
I woud like to try the modded sc also. Where can it be downloaded?

**Comment by stirante** [comment] 2016-11-02 16:57
We don't support modified version of snapchat, but It's interesting, that it can work just by changing version name. Right now I'm closing the issue.

**Closed as completed by stirante** 2016-11-02 16:57 UTC

**Comment by bobpaul** [comment] 2016-11-22 14:29
9.31.1.0  started crashing immediately on open last night and is no longer usable. Updated to 9.39.5, which works, but the link for the Snapprefs build in the comment above returns 404.
