### ISSUE TITLE
[MAJOR BUG]Snapchat/Snapprefs OBSOLETE for now due to serverside scan

### ISSUE THREAD

**Issue by Ryman2211** [marzika/Snapprefs#304] opened 2016-11-04 17:34 UTC
Snapchat must have put out an update today where it checks serverside to see if you're on an old Snapchat. As of this hour my Snapchat will automatically crash as soon as I open the app ONLY when connected to the internet. If I update to the newest version I can utilize Snapchat but not snapprefs.

**Comment by ghost** [comment] 2016-11-04 18:02
I have this too! Just happened a few hours ago! Snapprefs does not have anything to do with it, snapchat crashes too if I don't have the module / xposed itself activated!

Only solution to this (with snapprefs) is probably to update snapprefs to the newest snapchat version ..

_Also if you need any help @marzika, I am fairly good with java so if you have any annoying stuff to do you don't want to do, tell me and I can do it .. if that helps to get the next update sooner_

**Comment by ghost** [comment] 2016-11-04 18:07
Also, this is the exception crashing snapchat:

```
11-04 18:56:13.399 4016-4262/? E/AndroidRuntime: FATAL EXCEPTION: Misc-Pool-1
                                                 Process: com.snapchat.android, PID: 4016
                                                 java.lang.NullPointerException
                                                     at xz$1.run(SourceFile:1181)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                     at RA.run(SourceFile:19)
                                                     at java.lang.Thread.run(Thread.java:841)
```

As @Ryman2211 said, this only happens when there is an internet connection, so Snapchat probably changed something on their servers.

**Comment by Ryman2211** [comment] 2016-11-04 18:09
Oh no @fusionlightcat I wasn't saying it had anything to do with snapprefs! Sorry if I didn't communicate that well enough, I was just trying to point out for those that don't know what the hell is going on that Snapchat 9.31.1.0 is now obsolete therefore so is snapprefs at this moment. I wish I could help I just don't have much Java skill😂 I'm trying to learn bit I hated CS in high school

**Comment by ghost** [comment] 2016-11-04 18:10
I would love to support snapprefs but sadly I have no overview over the project structure and I am also not really sure how this injection stuff works .. lets just hope @marzika notices this bug

Also @Ryman2211, maybe you should make the title a bit more descriptive so that everyone sees that snapchat changed something server side and snapprefs needs an update to solve this problem :D

**Comment by M1kep** [comment] 2016-11-04 18:16
The issue is with SnapChat 9.31.1. It will be resolved in the upcoming release, in the meantime you can use the development build with 9.39.5

http://138.68.21.49:8080/job/SNAPPREFSDev/lastStableBuild/

**Comment by ghost** [comment] 2016-11-04 18:19
Perfect! Thanks!

**Closed as completed** 2016-11-04 18:33 UTC
